comments:
  waline: # 仅测试 waline 评论系统，其余评论系统可举一反三
    js: https://registry.npmmirror.com/@waline/client/3/files/dist/waline.umd.js
    css: https://registry.npmmirror.com/@waline/client/3/files/dist/waline.css
    emoji:
      - https://registry.npmmirror.com/@waline/emojis/1.2.0/files/weibo
      - https://registry.npmmirror.com/@waline/emojis/1.2.0/files/alus
      - https://registry.npmmirror.com/@waline/emojis/1.2.0/files/bilibili
      - https://registry.npmmirror.com/@waline/emojis/1.2.0/files/qq
      - https://registry.npmmirror.com/@waline/emojis/1.2.0/files/tieba
      - https://registry.npmmirror.com/@waline/emojis/1.2.0/files/tw-emoji
  
tag_plugins:
  video:
    js: https://registry.npmmirror.com/artplayer/5.1.6/files/dist/artplayer.js

plugins:
  jquery: https://registry.npmmirror.com/jquery/3.7.1/files/dist/jquery.min.js
  
  marked: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/marked/4.0.2/marked.min.js
  
  fancybox:
    js: https://registry.npmmirror.com/@fancyapps/ui/4.0.31/files/dist/fancybox.umd.js
    css: https://registry.npmmirror.com/@fancyapps/ui/4.0.31/files/dist/fancybox.css
  
  swiper:
    css: https://registry.npmmirror.com/swiper/11.1.5/files/swiper-bundle.min.css
    js: https://registry.npmmirror.com/swiper/11.1.5/files/swiper-bundle.min.js

  instant_click:
    js: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/instantclick/3.1.0/instantclick.min.js

  lazyload:
    js: https://registry.npmmirror.com/vanilla-lazyload/19.1.3/files/dist/lazyload.min.js
    transition: blur # blur, fade

  scrollreveal:
    js: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/scrollReveal.js/4.0.9/scrollreveal.min.js

  mathjax:
    cdn: https://registry.npmmirror.com/mathjax/3/files/es5/tex-mml-chtml.js #TODO: 跨版本测试

data_services:
  timeline: 
    ext:
      marked: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/marked/4.0.2/marked.min.js
  artplayer: 
    ext:
      artplayer: https://registry.npmmirror.com/artplayer/5.1.7/files/dist/artplayer.js
  music:
    css:
      APlayer: https://registry.npmmirror.com/aplayer/latest/files/dist/APlayer.min.css
    ext:
      APlayer: https://registry.npmmirror.com/aplayer/latest/files/dist/APlayer.min.js
      MetingJS: https://registry.npmmirror.com/meting/latest/files/dist/Meting.min.js



# 使用本地资源
# default:
#   avatar: /images/avatar.svg
#   link: /images/link.svg
#   cover: /images/cover.svg
#   image: /images/image.svg
#   banner: /images/banner.jpg
